
windows:
  # this keyboard shortcut will change to clipboard package
  shortcut: "Alt+p"
  add:
    salt: "randomSalt"
  generate:
    availabelChars: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
    numOfChars: 8


mac:
  shortcut: "Ctrl+p"
  add:
    salt: "randomSalt"
  generate:
    availabelChars: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
    numOfChars: 8